### ISSUE TITLE
Error Config

### ISSUE THREAD

**Issue by palmi** [christianbarkowsky/frontenduserimport#1]
Warning: strlen() expects parameter 1 to be string, array given in ((domain))/system/modules/frontenduserimport/config/config.php on line 17
#0 [internal function]: __error(2, 'strlen() expect...', '/((domain))', 17, Array)
#1 ((domain))/system/modules/frontenduserimport/config/config.php(17): strlen(Array)
#2 ((domain))/system/libraries/Config.php(155): include('/((domain))')
#3 ((domain))/system/libraries/Config.php(125): Config->initialize()
#4 ((domain))/system/initialize.php(74): Config::getInstance()
#5 ((domain))contao/main.php(36): require_once('((domain))')
#6 {main}

**Comment by christianbarkowsky** [comment]
Fixed
